### ISSUE TITLE
Version 17.1 includes simpler download instructions

### ISSUE THREAD

**Issue by arcfide** [markus1189/dyalog-nixos#1]
Version 17.1 of Dyalog APL has simplified the download process. Is there anything that must be done differently with this new process from the following download page?

https://www.dyalog.com/download-zone.htm

**Comment by markus1189** [comment]
Ahm yes, it seems like there are some libs missing now when building, I
will have a look later :)

**Comment by markus1189** [comment]
We can now automatically download dyalog, done in 5dc80d8e9c3b176adf0122258f78298a19b83fd0 :tada: 

I just had to include the `ncurses` lib as well
