### ISSUE TITLE
Mention nixpkgs

### ISSUE THREAD

**Issue by TomaSajt** [markus1189/dyalog-nixos#16]
My PR for RIDE finally got merged into nixpkgs recently, so it will make it into 24.05

I think we should update the README.md to point out that nixpkgs now has both dyalog and ride.

Not sure if this repository should be archived or repurposed or kept as is.

(I'm away on a trip, so I can't make a PR)

**Comment by markus1189** [comment]
Hey @TomaSajt ,

that's great news, thanks for sticking to it and seeing it merged :tada: 

I'll add a note :)
