### ISSUE TITLE
Keyboard instruction

### ISSUE THREAD

**Issue by Fresheyeball** [markus1189/dyalog-nixos#2]
It would be really nice if there was some instruction here about setting up the `apl` keyboard layout under nix.

**Comment by arcfide** [comment]
Does NixOS not contain the standard X.org or other windowing system symbol tables? If so, then changing the layout should be the same for Nix as for other Linux OSes. If not, I am also curious how you change keyboard layouts in Nix.

[Aaron W. Hsu (arcfide) - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=fa8fd)	[fa8fd]

On March 16, 2020 at 17:16 GMT, Isaac Shapira <notifications@github.com> wrote:

It would be really nice if there was some instruction here about setting up the apl keyboard layout under nix.

**Comment by markus1189** [comment]
There is nothing special, you can use setxkbmap as usual for example. In
theory you can use one of the nixos options to automatically set it, but
nothing prevents you from doing it in another way.
