### ISSUE TITLE
does this work currently?

### ISSUE THREAD

**Issue by shadowninja55** [markus1189/dyalog-nixos#5]
when using this i got a bunch of errors about `stdenv.lib` which i fixed by adding `lib` to the argument set and using that instead. however, now i'm getting a 404 on the .deb file which i don't know how to fix. any ideas?

**Comment by markus1189** [comment]
Can you please try again after updating? I updated the version, the old one was no longer available, therefore the 404 :)

**Comment by shadowninja55** [comment]
> Can you please try again after updating? I updated the version, the old one was no longer available, therefore the 404 :)

sure i can give it a shot, thanks!

**Comment by shadowninja55** [comment]
everything works perfect, thanks again :)
