### ISSUE TITLE
collision when including both dyalog and ride from overlay in packages

### ISSUE THREAD

**Issue by shadowninja55** [markus1189/dyalog-nixos#6]
it seems that alone, each package installs and runs fine. but if i try to rebuild with both packages in my environmentPackages at the same time i get a collision
> collision between `/nix/store/irn6x6s2l61cmq8rp60nyamhp8crs17k-ride-4.3.3463-1/natives_blob.bin' and `/nix/store/ky59n0fari51vqri63vpn7i5j0mc8p89-dyalog-18.0.40684/natives_blob.bin'

**Comment by markus1189** [comment]
Not sure if there is anything we can do for that.  Can you give me a small example that reproduces that issue?

**Comment by collares** [comment]
You can include `(lowPrio dyalog)` and `dyalog-ride` at the same time (or the other way around, if you prefer) to work around the collision.

**Comment by markus1189** [comment]
@shadowninja55 does the answer help you?

**Comment by shadowninja55** [comment]
> @shadowninja55 does the answer help you?

i'll try it out later, thanks
