### ISSUE TITLE
Implement a flake

### ISSUE THREAD

**Issue by subterfugue** [markus1189/dyalog-nixos#7]
Making a flake would allow running `nix run github:markus1189/dyalog-nixos` while getting an environment to run dyalog APL, which would be rather convenient.

**Comment by markus1189** [comment]
Agreed that would be really handy.  If anyone wants to contribute that, I'd be happy to review it.  I'm currently not really involved with APL anymore, so not sure if I will spend the time to do it

**Comment by subterfugue** [comment]
I'll PR it when I have the time. Thank you for your swift response.
