### ISSUE TITLE
RIDE hangs on splash screen

### ISSUE THREAD

**Issue by markus1189** [markus1189/dyalog-nixos#9]
No chance to investigate yet, but the RIDE IDE is stuck on the splash screen and does not work...

**Comment by bitmappergit** [comment]
It's because the version of RIDE in the github releases only works on electron 6, they haven't done a build since they updated it to work on 22.

**Comment by markus1189** [comment]
@bitmappergit thanks for the hint! I opened https://github.com/Dyalog/ride/issues/948

**Comment by TomaSajt** [comment]
After struggling a lot I finally finished writing a working derivation that can build the latest commit in the RIDE repo.
It uses the latest electron package (electron 24).

link: https://github.com/TomaSajt/dyalog-nixos/blob/c985b324f3ee9b1226ad7e4b04398a4d613e6bbd/ride.nix

If you want, I can open a pull request to update the derivation.

**Comment by markus1189** [comment]
I'd be happy about a pr :)

**Comment by markus1189** [comment]
Fixed by #10

**Comment by TomaSajt** [comment]
Now that this issue is resolved, should the Dyalog/ride issue be closed?
